- public-api/services.proto
Expose cluster stats endpoints on public-api.
- [NP-2382](https://nalej.atlassian.net/browse/NP-2382)
> NP-2382 expose cluster stats

- application-manager/entities.proto
- application-manager/services.proto
- public-api/entities.proto
- public-api/services.proto
- unified-logging/entities.proto
Improve unified Logging
- add `SearchRequest` and `Response` in public-api repo
- add new service `Unified-Logging` in application-manager repository
- update `SearchRequest` and `LogResponse` in `unified-logging` repo to include the new fields
- changed timestamp type from `google.protobuf.Timestamp` to `int64`
I have not included the `Expire` method in the application-manager, Needed?
- [NP-2283](https://nalej.atlassian.net/browse/NP-2283)
> NP-2283 Update Search method and structs for unified-logging

- application/entities.proto
- application/services.proto
- add `ListMetadatadaInstance` and the entities needed method in application repo
`Application-manager` needs this information to expand the info retrieved from `unified-logging`
- [NP-2421](https://nalej.atlassian.net/browse/NP-2421)
> NP-2421 add ListAppInstancesSchema method

- application/services.proto
add `GetAppInstanceReducedSummary` method that retrieves the reduced summary of a given application instance
- [NP-2363](https://nalej.atlassian.net/browse/NP-2363)
> NP-2363 GetAppInstanceReducedSummary added

- infrastructure/entities.proto
- public-api/entities.proto
Include the property `MillicoresConversionFactor` in the cluster definition and allows to update it through update request.
- [NP-2376](https://nalej.atlassian.net/browse/NP-2376)
> NP-2376 millicores conversion factor

- app-cluster-api/services.proto
the `Search` in unified-logging returns a list of responses 
- [NP-2364](https://nalej.atlassian.net/browse/NP-2364)
> NP-2364 app-cluster-api: search returns a list of responses

- infrastructure-manager/services.proto
- provisioner/entities.proto
- provisioner/services.proto
- public-api/entities.proto
- public-api/services.proto
* Add operations related to uninstall and decommission from public-api to infrastructure-manager
- [NP-2401](https://nalej.atlassian.net/browse/NP-2401)
> NP-2401 Cluster uninstall & decomission path

- public-api/entities.proto
* Add missing fields
- [NP-2401](https://nalej.atlassian.net/browse/NP-2401)
> Fix public api OpResponse

- conductor/entities.proto
Service added in the conductor component. This message contains service_name and service_group_name needed by deployment-manager to add labels with these values
- [NP-2433](https://nalej.atlassian.net/browse/NP-2433)
> NP-2433 Service added in conductor

- monitoring/entities.proto
- monitoring/services.proto
Generate new messages and RPCs to get the organization application stats.
- [NP-2379](https://nalej.atlassian.net/browse/NP-2379)
> NP-2379 Get org stats

- unified-logging/entities.proto
updates the names in unified-logging.LogResponse message
- [NP-2364](https://nalej.atlassian.net/browse/NP-2361)
> NP-2364 logResponse updated

- app-cluster-api/services.proto
- monitoring/services.proto
Add new RPCs to the app-cluster-api to allow communication.
- [NP-2379](https://nalej.atlassian.net/browse/NP-2379)
> NP-2379 Add new RPCs to the app-cluster-api to allow communication

- conductor/entities.proto
Added service name to public security rule.
- [NP-2439](https://nalej.atlassian.net/browse/NP-2439)
> Added service name to public security rule.

- monitoring/entities.proto
Include `appInstanceId` and `Image` to the stats (image can be useful for debugging and benchmarking purposes).
- [NP-2388](https://nalej.atlassian.net/browse/NP-2388)
> NP-2388 Include useful properties to the stats.

- user/entities.proto
Updated UpdateUserRequest.
- [NP-2470](https://nalej.atlassian.net/browse/NP-2470)
> NP-2470 updated UpdateUserRequest

- public-api/entities.proto
- public-api/services.proto
- Add Download message in public-api unifiedLogging services
- Add Check message in public-api unifiedLogging services
- Fix a bug in Search URL
- [NP-2480](https://nalej.atlassian.net/browse/NP-2480)
> NP-2480 Download added in public-api

- user/entities.proto
added bools to update user request
- [NP-2470](https://nalej.atlassian.net/browse/NP-2470)
> NP-2470 added bools to update user request

- monitoring/services.proto
Include organization ID temporarily on the path to use it without certificates.
- [NP-2384](https://nalej.atlassian.net/browse/NP-2384)
> NP-2384 Include OrganizationId on the path temporarily.

- monitoring/services.proto
- [NP-2384](https://nalej.atlassian.net/browse/NP-2384)
> NP-2384 Include POST method on the metrics endpoint.

- application/entities.proto
Adds Endpoint options in the Endpoint field. This field allows the user to configure the endpoint 
- [NP-2452](https://nalej.atlassian.net/browse/NP-2452)
> NP-2452 Endpoint Options added

- public-api/entities.proto
include the Options field in public-api.AppInstance
- [NP-2454](https://nalej.atlassian.net/browse/NP-2454)
> NP-2454 EndpointOptions added in public-api.appInstace

- organization/entities.proto
add new fields to organization
- [NP-2474](https://nalej.atlassian.net/browse/NP-2474)
> NP-2474 Organization updated

- organization/entities.proto
Fix a bug in UpdateOrganizationRequest. The update flags were string and they have to be bool fields
- [NP-2474](https://nalej.atlassian.net/browse/NP-2474)
> NP-2474 update flags in UpdateOrganizationRequest changed to bool

- organization-manager/services.proto
GetSetting was no returned organization identifier
- [NP-2475](https://nalej.atlassian.net/browse/NP-2475)
> NP-2475 GetSetting returned object include the organization_id

- public-api/services.proto
updates the message organization Info in public api
adds a new message to update the organization
- [NP-2524](https://nalej.atlassian.net/browse/NP-2524)
> NP-2524 organization info in public-api updated

- public-api/entities.proto
RoleName changed to RoleId in addUserRequest struct
- [NP-XX](https://nalej.atlassian.net/browse/NP-XX)
> NP-XX addUserRequest changed. RoleName changed to RoleId

- public-api/entities.proto
- public-api/services.proto
adds `OrganizationSetting` messages in public-api
- [NP-2527](https://nalej.atlassian.net/browse/NP-2527)
> NP-2527 organization setting public api

- public-api/entities.proto
- public-api/services.proto
the user can decide to list the setting ascending or descending. This field has been included in the request
- [NP-2540](https://nalej.atlassian.net/browse/NP-2540)
> NP-2540 list Setting Request include a field to indicate the order

- organization-manager/entities.proto
- public-api/entities.proto
Created field added to organization-manager.Organization
fix a bug in the index of ListRequest
- [NP-2526](https://nalej.atlassian.net/browse/NP-2526)
> NP-2526 created field added to organization-manager.Organization

- organization/entities.proto
add an enum to define the allowed settings
- [NP-XXX](https://nalej.atlassian.net/browse/NP-XXX)
> NP-XX allowed setting keys added

- authx/entities.proto
Unnecessary field in UserAuthxInfo removed
- [NP-2559](https://nalej.atlassian.net/browse/NP-2559)
> NP-2559 unnecessary field in UserAuthxInfo removed

- public-api/entities.proto
- signup/entities.proto
Include the new organization fields in signup and public API protos.
- [NP-2533](https://nalej.atlassian.net/browse/NP-2533)
> NP-2533 org required fields

- signup/entities.proto
Include the organization photo base64 string on the signup request.
- [NP-2533](https://nalej.atlassian.net/browse/NP-2533)
> NP-2553 Process org photo on signup

- organization-manager/entities.proto
- organization/entities.proto
- signup/entities.proto
Includes the email as an organization mandatory field.
- [NP-2616](https://nalej.atlassian.net/browse/NP-2616)
> NP-2616 Add email to organization.

- signup/entities.proto
Include last name and title properties on the signup request for the owner and Nalej admin.
These properties are going to be required.
- [NP-2534](https://nalej.atlassian.net/browse/NP-2534)
> NP-2534 Include last name and title properties on the signup request

- authx/entities.proto
- user-manager/entities.proto
Removes the password from ChangePasswordRequest message
- [NP-2532](https://nalej.atlassian.net/browse/NP-2532)
> NP-2532 old password deleted from ChangePasswordRequest

- public-api/services.proto
Adds Order when listing clusters
- [NP-2564](https://nalej.atlassian.net/browse/NP-2564)
> NP-2564 order added when listing clusters

- authx/entities.proto
- authx/services.proto
- public-api/services.proto
Include all the messages and procedures to implement the management of monitoring certificates through API.
- [NP-2377](https://nalej.atlassian.net/browse/NP-2377)
> NP-2377 Generate messages and RPCs to manage monitoring certificates
